### PR TITLE
End of Spring 2020

### PR DESCRIPTION
**Pull request by C-SELLERS**
Changes:
- Removal of some dead test code
- Addition of UART to CAN Test code for demoing control of low level systems
- Commented out gyroscope in localization
- Change to debug printing of speed from mm/s to m/s
- Move Kalman and Matrix objects to archives located elsewhere

Not a lot of major changes as we focused more on the simulator. There is definitely work that needs to be done in order for the high level to function on its own.

### CODE REVIEW

**Comment by TylerFolsom** [comment]
Does the code from Copper Hill belong in our repo? HighLevel_UART_to_CAN_demo.ino is problematic, since it blocks any other HighLevel processing.
Why is LatLontoMM no longer used? What has replaced it? Why no AcquireGPRMC, GPGGA?
Why is the origin set for the soccer field? The design is to use the current location as an index into available maps, and select the map origin. For simulation, it should be the origin for CARLA town.
Is there ny harm in leaving in the Gyro methods?

**Review by TylerFolsom — COMMENTED** [review]
Kalman code was changed 11 months ago, and is newer than the code in Elcano/Elcano. It should not be deleted.
Most of the directories in HighLevel are garbage. We should only keep the HighLevel and SD card directories. There should be a series of if statements or #ifdef flags that disable code for testing. There should be one version of HighLevel that can be built for full or partial functionality.

**Comment by TylerFolsom** [comment]
There is still the problem of removing Kalman code and GPS methods.

**Comment by C-SELLERS** [comment]
Code has been added again!

**Comment by C-SELLERS** [comment]
SNAFU flag will stop it from compiling

**Comment by C-SELLERS** [comment]
Just made some small changes from what I saw. This is a little cleaner and keeps the High_Level directory as the only full high level code. In the future we need to use branches for testing changes to this directory.

**Comment by C-SELLERS** [comment]
I did keep the test sketches in their directory as they aren't the same as a complete high level. Although I agree moving forward these types of testing should be managed in a separate branch dedicated to those tests.

**Pull request merged**
